name: Deploy DEVELOP

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: [self-hosted, rjma, backend]

    steps:
      - name: Deploy develop
        run: |
          sudo -n /mnt/fastpool/apps/rjma-develop/scripts/deploy-develop.sh
